TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += aldn1000.db
DB += unit_setter.db
DATA += aldn1000.proto

#=======================================
include $(TOP)/configure/RULES
